---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: python
    tag: '3.7-slim'
params:
inputs:
  - name: shop-catalog-api
outputs:
  - name: dist

run:
  path: sh
  args:
    - -exc
    - |
      cd shop-catalog-api/deploy/scripts/ && chmod +x 'build.sh'
      . ./'build.sh'