---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: hashicorp/terraform
    tag: '0.11.10'
params:
  AWS_ACCESS_KEY_ID: ((nonprod_aws_access_key))
  AWS_SECRET_ACCESS_KEY: ((nonprod_aws_secret_key))
inputs:
  - name: shop-catalog-api
outputs:
run:
  path: sh
  args:
    - -exc
    - |
      cd shop-catalog-api/deploy/scripts/ && chmod +x 'terraform_apply.sh'
      . ./'terraform_apply.sh'